<?php
/**
 * Implementation of hook_wysiwyg_editor_settings_alter().
 */
function customize_tinymce_wysiwyg_editor_settings_alter(&$settings, $context) {
    if ($context['profile'] -> editor == 'tinymce') {
        // Add custom styles for the styleselect plugin.
            $settings['style_formats'] = array(
                array(
                    'title' => 'Heading highlighted',
                    'inline' => 'span', 'classes' => 'highlight'
                ),
                array(
                    'title' => 'Heading 1',
                    'block' => 'h1',
                    'classes' => 'heading-1'
                ),
                array(
                    'title' => 'Heading 2',
                    'block' => 'h2',
                    'classes' => 'heading-2'
                ),
                array(
                    'title' => 'Heading 3',
                    'block' => 'h3',
                    'classes' => 'heading-3'
                ),
                array(
                    'title' => 'Heading 4',
                    'block' => 'h4',
                    'classes' => 'heading-4'
                ),
                array(
                    'title' => 'Lien PDF',
                    'inline' => 'a',
                    'classes' => 'wsf-btn pdf',
                ),
                array(
                    'title' => 'Texte',
                    'block' => 'p',
                    'classes' => 'texte'
                ),
                array(
                    'title' => 'Texte emphasis',
                    'inline' => 'span',
                    'classes' => 'texte-emphasis'
                ),
                array(
                    'title' => 'Accordéon - Question',
                    'block' => 'p',
                    'classes' => 'acc-head'
                ),
                array(
                    'title' => 'Accordéon - Réponse',
                    'block' => 'p',
                    'classes' => 'acc-resp'
                ),
        // etc.
        );
    }
}